In [22]:
import os
import subprocess
import numpy as np
import pandas as pd
import seaborn as sns

In [23]:
def find_files(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            yield os.path.join(root, file)


# ===== 修改为 decompress.ipynb 生成的 chunk 目录 =====
directory_to_search = '/home/user/data/partial_data_ubuntu_512KiB/'
all_files = list(find_files(directory_to_search))

print(f'chunk number: {len(all_files)}')

chunk number: 3584

In [24]:
print(all_files[0])

/home/user/data/partial_data_ubuntu_512KiB/ubuntu_lunar-20230415_layer_33_block_26.bin

# 1. LSH-based MLE

## Multiprocess to calculate

In [25]:
import os
import subprocess
import numpy as np
import pandas as pd
import seaborn as sns

import subprocess
import pandas as pd
from multiprocessing import Pool

def find_files(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            yield os.path.join(root, file)


# directory_to_search = './uncompressed_data_ubuntu_4KiB/'
# all_files = list(find_files(directory_to_search))

print(f'chunk number: {len(all_files)}')


def process_file(file):
    status, output = subprocess.getstatusoutput('./finesse ' + file + ' 48 3 12')
    output = output.split('\n')
    h = output[0].split(': ')[-1]
    sf1 = output[1]
    sf2 = output[2]
    sf3 = output[3]
    return file, h, sf1, sf2, sf3

# def process_main():
all_files = list(find_files(directory_to_search))  
print(f"Total files: {len(all_files)}")
pool_size = 30  # Adjust based on your system capability

sfs = []
with Pool(pool_size) as p:
    for i, result in enumerate(p.imap(process_file, all_files), 1):
        sfs.append(result)
        if i % 10000 == 0:
            print(f"Processed {i}/{len(all_files)} files")

print('\nFinish parallel computing')
sfs_pd = pd.DataFrame(sfs, columns=['file name', 'h', 'sf1', 'sf2', 'sf3'])

# print(sfs_pd)

# sfs_pd.to_pickle('./sfs_pd_partial_data_pytorch_512KiB.pkl')

# process_main()

chunk number: 3584
Total files: 3584

Finish parallel computing

In [14]:
sfs_pd.to_pickle('./sfs_pd(partial_data_ubuntu).pkl')

In [12]:
sfs_pd.describe()

,file name,h,sf1,sf2,sf3
count,3584,3584,3584,3584,3584
unique,3584,2989,1704,1624,1368
top,/home/user/data/partial_data_ubuntu_512KiB/ubu...,812372314781133781,3568976612918044448,6849166359721366723,-6501048734054152159
freq,1,3,13,15,19

In [13]:
sfs_pd['sf3'].value_counts()

sf3
-6501048734054152159    19
5689966320291996564     18
-1142809568002161927    17
-7264128716306727247    16
6131137648532884986     15
                        ..
2766077846710300591      1
4258644391146202415      1
197047752082090869       1
-3631135908072267659     1
-7316550525581742857     1
Name: count, Length: 1368, dtype: int64

In [16]:

sf3_counts = sfs_pd['sf3'].value_counts()  

sf3_counts = sf3_counts - 1  
  
 
total = sf3_counts.sum()  
  
# Print the finesse results 
print("The total sum after subtracting 1 from each count is: ", total) 
print(total*512/1024/1024)

The total sum after subtracting 1 from each count is:  48480
23.671875

# Use fastcdc for the finesse results

In [15]:
new_df = sfs_pd.groupby('sf3')['file name'].agg(lambda x: list(x)).reset_index()  
new_df.columns = ['sf3', 'file name'] 
new_df

                       sf3                                          file name
0     -1013891271140676130  [/home/user/data/partial_data_ubuntu_512KiB/ub...
1     -1015925232259320187  [/home/user/data/partial_data_ubuntu_512KiB/ub...
2     -1046086924293833932  [/home/user/data/partial_data_ubuntu_512KiB/ub...
3     -1055869152482771371  [/home/user/data/partial_data_ubuntu_512KiB/ub...
4     -1070130410644024007  [/home/user/data/partial_data_ubuntu_512KiB/ub...
...                    ...                                                ...
1363     92775482735558017  [/home/user/data/partial_data_ubuntu_512KiB/ub...
1364    932069116995599158  [/home/user/data/partial_data_ubuntu_512KiB/ub...
1365    966072651097794167  [/home/user/data/partial_data_ubuntu_512KiB/ub...
1366    970997905746111340  [/home/user/data/partial_data_ubuntu_512KiB/ub...
1367    974276917664677176  [/home/user/data/partial_data_ubuntu_512KiB/ub...

[1368 rows x 2 columns]

In [16]:
new_df = new_df[new_df['file name'].apply(lambda x: len(x) > 1)]  
new_df = new_df.reset_index(drop=True)  
new_df

                      sf3                                          file name
0    -1015925232259320187  [/home/user/data/partial_data_ubuntu_512KiB/ub...
1    -1046086924293833932  [/home/user/data/partial_data_ubuntu_512KiB/ub...
2    -1114725842920054983  [/home/user/data/partial_data_ubuntu_512KiB/ub...
3    -1136049125181639519  [/home/user/data/partial_data_ubuntu_512KiB/ub...
4    -1142809568002161927  [/home/user/data/partial_data_ubuntu_512KiB/ub...
..                    ...                                                ...
774   9111668364512978263  [/home/user/data/partial_data_ubuntu_512KiB/ub...
775    919841604400590499  [/home/user/data/partial_data_ubuntu_512KiB/ub...
776     92775482735558017  [/home/user/data/partial_data_ubuntu_512KiB/ub...
777    932069116995599158  [/home/user/data/partial_data_ubuntu_512KiB/ub...
778    974276917664677176  [/home/user/data/partial_data_ubuntu_512KiB/ub...

[779 rows x 2 columns]

In [17]:
import multiprocessing
from fastcdc import fastcdc
from hashlib import sha256

num_process=30

def process_file(file_name):
    # status, output = subprocess.getstatusoutput('fastcdc -mi 256 -s 512 -ma 1024 ' + file_name)
    # output = output.split('\n')
    results = []
    output = list(fastcdc(file_name, 256, 512, 1024, fat=True, hf=sha256))
    for i in range(len(output)):
        results.append([file_name, output[i].hash, output[i].length])
    # for line in output:
    #     temp = line.split(' ')
    #     temp_hash = temp[0].split('=')[-1]
    #     temp_offset = temp[1].split('=')[-1]
    #     temp_size = temp[2].split('=')[-1]
    #     results.append([file_name, temp_hash, temp_size])
    return results

def get_reduce_ration(fastcdc_df):

    fastcdc_df['size'] = fastcdc_df['size'].astype(int)

    # Calculate the total size of each hash value
    hash_total_size = fastcdc_df.groupby('hash')['size'].sum()

    # Calculate the number of occurrences of each hash
    hash_counts = fastcdc_df['hash'].value_counts()
    hashes_more_than_once = hash_counts[hash_counts > 1].index
    duplicated_first_instances = fastcdc_df[fastcdc_df['hash'].isin(hashes_more_than_once)].drop_duplicates('hash')
    size_sum_duplicated_first = duplicated_first_instances['size'].sum()
    
    hashes_once_only = hash_counts[hash_counts == 1].index
    instances_once_only = fastcdc_df[fastcdc_df['hash'].isin(hashes_once_only)]
    size_sum_once_only = instances_once_only['size'].sum()
    
    # Calculate the redundant size: for each hash, its total size minus the size of the first instance
    reduced_size = (hash_total_size - fastcdc_df.drop_duplicates('hash').set_index('hash')['size']).sum()
    
    
    # Calculate the total size
    total_size = hash_total_size.sum()

    # print(f"reduce size is {reduced_size}")
    # print(f"all size is {total_size}")
    return reduced_size, total_size, size_sum_duplicated_first, size_sum_once_only

def get_cluster(cluster_id):
    fastcdc_list = []
    cluster_files = new_df.iloc[cluster_id].at['file name']

    with multiprocessing.Pool(processes=num_process) as pool:
        results = pool.map(process_file, cluster_files)
        for result in results:
            fastcdc_list.extend(result)

    fastcdc_df = pd.DataFrame(fastcdc_list, columns=['file name', 'hash', 'size'])
    return fastcdc_df


all_cluster_size = []
all_cluster_reducesize = []
all_cluster_sum_duplicated_first = []
all_cluster_sum_once_only = []

for cluster_id in range(new_df.shape[0]):
    # print(f"cluster:{cluster_id}")
    temp_df = get_cluster(cluster_id)
    temp_reduce, temp_all, temp_size_sum_duplicated_first, temp_size_sum_once_only = get_reduce_ration(temp_df)
    print(f"cluster:{cluster_id}, reduced size:{temp_reduce}, cluster total size: {temp_all}, duplicated first: {temp_size_sum_duplicated_first}, once_only: {temp_size_sum_once_only}")
    all_cluster_size.append(temp_all)
    all_cluster_reducesize.append(temp_reduce)
    all_cluster_sum_duplicated_first.append(temp_size_sum_duplicated_first)
    all_cluster_sum_once_only.append(temp_size_sum_once_only)

total = sum(all_cluster_size)
total_reduce = sum(all_cluster_reducesize)
total_duplicated_first = sum(all_cluster_sum_duplicated_first)
total_once_only = sum(all_cluster_sum_once_only)

print("{} {} {}".format(total_reduce, total, total_reduce * 1.0 / total))
print(f'total reduced: {total_reduce/1024/1024/1024}GB')
print(f'total: {total/1024/1024/1024}GB')
print(f'total duplicated first: {total_duplicated_first/1024/1024/1024}GB')
print(f'total once only: {total_once_only/1024/1024/1024}GB')

cluster:0, reduced size:1114679, cluster total size: 1572864, duplicated first: 363594, once_only: 94591
cluster:1, reduced size:1523893, cluster total size: 2097152, duplicated first: 513961, once_only: 59298
cluster:2, reduced size:530666, cluster total size: 1048576, duplicated first: 517910, once_only: 0
cluster:3, reduced size:1572417, cluster total size: 2097152, duplicated first: 524288, once_only: 447
cluster:4, reduced size:8134764, cluster total size: 8912896, duplicated first: 598133, once_only: 179999
cluster:5, reduced size:485079, cluster total size: 1048576, duplicated first: 485079, once_only: 78418
cluster:6, reduced size:2463393, cluster total size: 3145728, duplicated first: 626318, once_only: 56017
cluster:7, reduced size:2682540, cluster total size: 3145728, duplicated first: 402799, once_only: 60389
cluster:8, reduced size:1017038, cluster total size: 1572864, duplicated first: 513654, once_only: 42172
cluster:9, reduced size:1557808, cluster total size: 2097152, duplicated first: 524288, once_only: 15056
cluster:10, reduced size:1514213, cluster total size: 2097152, duplicated first: 517758, once_only: 65181
cluster:11, reduced size:508490, cluster total size: 1048576, duplicated first: 508490, once_only: 31596
cluster:12, reduced size:3546631, cluster total size: 4194304, duplicated first: 549481, once_only: 98192
cluster:13, reduced size:2491697, cluster total size: 3145728, duplicated first: 541825, once_only: 112206
cluster:14, reduced size:490531, cluster total size: 1048576, duplicated first: 486445, once_only: 71600
cluster:15, reduced size:2503101, cluster total size: 3145728, duplicated first: 580767, once_only: 61860
cluster:16, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:17, reduced size:370254, cluster total size: 1048576, duplicated first: 365134, once_only: 313188
cluster:18, reduced size:1560998, cluster total size: 2097152, duplicated first: 524288, once_only: 11866
cluster:19, reduced size:2053303, cluster total size: 2621440, duplicated first: 521632, once_only: 46505
cluster:20, reduced size:3017439, cluster total size: 3670016, duplicated first: 527082, once_only: 125495
cluster:21, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:22, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:23, reduced size:2063903, cluster total size: 2621440, duplicated first: 524354, once_only: 33183
cluster:24, reduced size:3007217, cluster total size: 3670016, duplicated first: 536232, once_only: 126567
cluster:25, reduced size:533305, cluster total size: 1048576, duplicated first: 515271, once_only: 0
cluster:26, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:27, reduced size:1545673, cluster total size: 2097152, duplicated first: 523785, once_only: 27694
cluster:28, reduced size:525164, cluster total size: 1048576, duplicated first: 523412, once_only: 0
cluster:29, reduced size:1552349, cluster total size: 2097152, duplicated first: 524288, once_only: 20515
cluster:30, reduced size:1103530, cluster total size: 1572864, duplicated first: 469334, once_only: 0
cluster:31, reduced size:1472513, cluster total size: 2097152, duplicated first: 556591, once_only: 68048
cluster:32, reduced size:2513251, cluster total size: 3145728, duplicated first: 535402, once_only: 97075
cluster:33, reduced size:580168, cluster total size: 1048576, duplicated first: 468408, once_only: 0
cluster:34, reduced size:2530987, cluster total size: 3145728, duplicated first: 513337, once_only: 101404
cluster:35, reduced size:2019294, cluster total size: 2621440, duplicated first: 514463, once_only: 87683
cluster:36, reduced size:3509909, cluster total size: 4194304, duplicated first: 555936, once_only: 128459
cluster:37, reduced size:505610, cluster total size: 1048576, duplicated first: 505610, once_only: 37356
cluster:38, reduced size:4527364, cluster total size: 5242880, duplicated first: 529482, once_only: 186034
cluster:39, reduced size:2565770, cluster total size: 3145728, duplicated first: 528604, once_only: 51354
cluster:40, reduced size:524902, cluster total size: 1048576, duplicated first: 523674, once_only: 0
cluster:41, reduced size:2490216, cluster total size: 3145728, duplicated first: 538174, once_only: 117338
cluster:42, reduced size:489719, cluster total size: 1048576, duplicated first: 489719, once_only: 69138
cluster:43, reduced size:486225, cluster total size: 1048576, duplicated first: 486225, once_only: 76126
cluster:44, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:45, reduced size:2545750, cluster total size: 3145728, duplicated first: 522021, once_only: 77957
cluster:46, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:47, reduced size:2501400, cluster total size: 3145728, duplicated first: 560547, once_only: 83781
cluster:48, reduced size:1550560, cluster total size: 2097152, duplicated first: 519413, once_only: 27179
cluster:49, reduced size:1554686, cluster total size: 2097152, duplicated first: 521546, once_only: 20920
cluster:50, reduced size:620229, cluster total size: 1048576, duplicated first: 428347, once_only: 0
cluster:51, reduced size:511017, cluster total size: 1048576, duplicated first: 511017, once_only: 26542
cluster:52, reduced size:2047043, cluster total size: 2621440, duplicated first: 523147, once_only: 51250
cluster:53, reduced size:491615, cluster total size: 1048576, duplicated first: 491615, once_only: 65346
cluster:54, reduced size:552443, cluster total size: 1048576, duplicated first: 496133, once_only: 0
cluster:55, reduced size:1003643, cluster total size: 1572864, duplicated first: 523221, once_only: 46000
cluster:56, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:57, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:58, reduced size:2542764, cluster total size: 3145728, duplicated first: 552921, once_only: 50043
cluster:59, reduced size:4004527, cluster total size: 4718592, duplicated first: 540787, once_only: 173278
cluster:60, reduced size:1048576, cluster total size: 1572864, duplicated first: 524288, once_only: 0
cluster:61, reduced size:1006063, cluster total size: 1572864, duplicated first: 508397, once_only: 58404
cluster:62, reduced size:1911887, cluster total size: 2621440, duplicated first: 522858, once_only: 186695
cluster:63, reduced size:1486993, cluster total size: 2097152, duplicated first: 524012, once_only: 86147
cluster:64, reduced size:488752, cluster total size: 1048576, duplicated first: 488752, once_only: 71072
cluster:65, reduced size:2539053, cluster total size: 3145728, duplicated first: 502703, once_only: 103972
cluster:66, reduced size:1545841, cluster total size: 2097152, duplicated first: 524006, once_only: 27305
cluster:67, reduced size:513608, cluster total size: 1048576, duplicated first: 508324, once_only: 26644
cluster:68, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:69, reduced size:2570126, cluster total size: 3145728, duplicated first: 536114, once_only: 39488
cluster:70, reduced size:509028, cluster total size: 1048576, duplicated first: 509028, once_only: 30520
cluster:71, reduced size:1560140, cluster total size: 2097152, duplicated first: 521448, once_only: 15564
cluster:72, reduced size:2525346, cluster total size: 3145728, duplicated first: 566618, once_only: 53764
cluster:73, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:74, reduced size:2456583, cluster total size: 3145728, duplicated first: 600941, once_only: 88204
cluster:75, reduced size:1499283, cluster total size: 2097152, duplicated first: 524288, once_only: 73581
cluster:76, reduced size:441775, cluster total size: 1048576, duplicated first: 424765, once_only: 182036
cluster:77, reduced size:2029747, cluster total size: 2621440, duplicated first: 528402, once_only: 63291
cluster:78, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:79, reduced size:1508890, cluster total size: 2097152, duplicated first: 527804, once_only: 60458
cluster:80, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:81, reduced size:1485848, cluster total size: 2097152, duplicated first: 531002, once_only: 80302
cluster:82, reduced size:3022953, cluster total size: 3670016, duplicated first: 539842, once_only: 107221
cluster:83, reduced size:2050971, cluster total size: 2621440, duplicated first: 527569, once_only: 42900
cluster:84, reduced size:2034946, cluster total size: 2621440, duplicated first: 509600, once_only: 76894
cluster:85, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:86, reduced size:1506191, cluster total size: 2097152, duplicated first: 515229, once_only: 75732
cluster:87, reduced size:469756, cluster total size: 1048576, duplicated first: 469756, once_only: 109064
cluster:88, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:89, reduced size:1548403, cluster total size: 2097152, duplicated first: 524288, once_only: 24461
cluster:90, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:91, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:92, reduced size:2054603, cluster total size: 2621440, duplicated first: 529684, once_only: 37153
cluster:93, reduced size:1331791, cluster total size: 2097152, duplicated first: 487946, once_only: 277415
cluster:94, reduced size:3076357, cluster total size: 3670016, duplicated first: 526968, once_only: 66691
cluster:95, reduced size:2015231, cluster total size: 2621440, duplicated first: 529234, once_only: 76975
cluster:96, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:97, reduced size:490592, cluster total size: 1048576, duplicated first: 490592, once_only: 67392
cluster:98, reduced size:484768, cluster total size: 1048576, duplicated first: 484768, once_only: 79040
cluster:99, reduced size:3512130, cluster total size: 4194304, duplicated first: 555021, once_only: 127153
cluster:100, reduced size:2043055, cluster total size: 2621440, duplicated first: 521136, once_only: 57249
cluster:101, reduced size:591872, cluster total size: 1048576, duplicated first: 456704, once_only: 0
cluster:102, reduced size:5147616, cluster total size: 5767168, duplicated first: 397180, once_only: 222372
cluster:103, reduced size:941529, cluster total size: 1572864, duplicated first: 488541, once_only: 142794
cluster:104, reduced size:2069817, cluster total size: 2621440, duplicated first: 527482, once_only: 24141
cluster:105, reduced size:3507005, cluster total size: 4194304, duplicated first: 555940, once_only: 131359
cluster:106, reduced size:472677, cluster total size: 1048576, duplicated first: 466505, once_only: 109394
cluster:107, reduced size:1894721, cluster total size: 2621440, duplicated first: 660668, once_only: 66051
cluster:108, reduced size:2034048, cluster total size: 2621440, duplicated first: 554735, once_only: 32657
cluster:109, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:110, reduced size:2503740, cluster total size: 3145728, duplicated first: 565296, once_only: 76692
cluster:111, reduced size:527497, cluster total size: 1048576, duplicated first: 521079, once_only: 0
cluster:112, reduced size:4007497, cluster total size: 4718592, duplicated first: 564391, once_only: 146704
cluster:113, reduced size:2477946, cluster total size: 3145728, duplicated first: 567119, once_only: 100663
cluster:114, reduced size:2019676, cluster total size: 2621440, duplicated first: 545191, once_only: 56573
cluster:115, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:116, reduced size:507051, cluster total size: 1048576, duplicated first: 507051, once_only: 34474
cluster:117, reduced size:2843380, cluster total size: 3670016, duplicated first: 567374, once_only: 259262
cluster:118, reduced size:3012526, cluster total size: 3670016, duplicated first: 529277, once_only: 128213
cluster:119, reduced size:525456, cluster total size: 1048576, duplicated first: 523120, once_only: 0
cluster:120, reduced size:3334966, cluster total size: 4194304, duplicated first: 757322, once_only: 102016
cluster:121, reduced size:2067433, cluster total size: 2621440, duplicated first: 525355, once_only: 28652
cluster:122, reduced size:445761, cluster total size: 1048576, duplicated first: 443955, once_only: 158860
cluster:123, reduced size:488889, cluster total size: 1048576, duplicated first: 468090, once_only: 91597
cluster:124, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:125, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:126, reduced size:2767565, cluster total size: 3145728, duplicated first: 341507, once_only: 36656
cluster:127, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:128, reduced size:2900807, cluster total size: 3670016, duplicated first: 639667, once_only: 129542
cluster:129, reduced size:1430583, cluster total size: 2097152, duplicated first: 590755, once_only: 75814
cluster:130, reduced size:503108, cluster total size: 1048576, duplicated first: 496098, once_only: 49370
cluster:131, reduced size:503942, cluster total size: 1048576, duplicated first: 503942, once_only: 40692
cluster:132, reduced size:525510, cluster total size: 1048576, duplicated first: 523066, once_only: 0
cluster:133, reduced size:525661, cluster total size: 1048576, duplicated first: 522915, once_only: 0
cluster:134, reduced size:3015351, cluster total size: 3670016, duplicated first: 533781, once_only: 120884
cluster:135, reduced size:2519730, cluster total size: 3145728, duplicated first: 537347, once_only: 88651
cluster:136, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:137, reduced size:2927937, cluster total size: 3670016, duplicated first: 543127, once_only: 198952
cluster:138, reduced size:2020278, cluster total size: 2621440, duplicated first: 524924, once_only: 76238
cluster:139, reduced size:3068480, cluster total size: 3670016, duplicated first: 522634, once_only: 78902
cluster:140, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:141, reduced size:2054720, cluster total size: 2621440, duplicated first: 525688, once_only: 41032
cluster:142, reduced size:5500014, cluster total size: 6291456, duplicated first: 629323, once_only: 162119
cluster:143, reduced size:1459390, cluster total size: 2097152, duplicated first: 595733, once_only: 42029
cluster:144, reduced size:485306, cluster total size: 1048576, duplicated first: 485306, once_only: 77964
cluster:145, reduced size:2540721, cluster total size: 3145728, duplicated first: 546683, once_only: 58324
cluster:146, reduced size:757872, cluster total size: 1572864, duplicated first: 427155, once_only: 387837
cluster:147, reduced size:1014802, cluster total size: 1572864, duplicated first: 505869, once_only: 52193
cluster:148, reduced size:500593, cluster total size: 1048576, duplicated first: 500593, once_only: 47390
cluster:149, reduced size:496213, cluster total size: 1048576, duplicated first: 485261, once_only: 67102
cluster:150, reduced size:500544, cluster total size: 1048576, duplicated first: 500544, once_only: 47488
cluster:151, reduced size:489949, cluster total size: 1048576, duplicated first: 481831, once_only: 76796
cluster:152, reduced size:1048576, cluster total size: 1572864, duplicated first: 524288, once_only: 0
cluster:153, reduced size:1517192, cluster total size: 2097152, duplicated first: 511022, once_only: 68938
cluster:154, reduced size:2526404, cluster total size: 3145728, duplicated first: 562096, once_only: 57228
cluster:155, reduced size:483531, cluster total size: 1048576, duplicated first: 482371, once_only: 82674
cluster:156, reduced size:4026850, cluster total size: 4718592, duplicated first: 555950, once_only: 135792
cluster:157, reduced size:1523394, cluster total size: 2097152, duplicated first: 515059, once_only: 58699
cluster:158, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:159, reduced size:505937, cluster total size: 1048576, duplicated first: 505937, once_only: 36702
cluster:160, reduced size:2031115, cluster total size: 2621440, duplicated first: 517919, once_only: 72406
cluster:161, reduced size:525748, cluster total size: 1048576, duplicated first: 522828, once_only: 0
cluster:162, reduced size:375879, cluster total size: 1048576, duplicated first: 375879, once_only: 296818
cluster:163, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:164, reduced size:2550193, cluster total size: 3145728, duplicated first: 513158, once_only: 82377
cluster:165, reduced size:4083025, cluster total size: 4718592, duplicated first: 566811, once_only: 68756
cluster:166, reduced size:3344525, cluster total size: 4194304, duplicated first: 751177, once_only: 98602
cluster:167, reduced size:524872, cluster total size: 1048576, duplicated first: 523704, once_only: 0
cluster:168, reduced size:507334, cluster total size: 1048576, duplicated first: 506676, once_only: 34566
cluster:169, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:170, reduced size:3056588, cluster total size: 3670016, duplicated first: 516945, once_only: 96483
cluster:171, reduced size:2064743, cluster total size: 2621440, duplicated first: 526830, once_only: 29867
cluster:172, reduced size:1191831, cluster total size: 1572864, duplicated first: 316045, once_only: 64988
cluster:173, reduced size:510495, cluster total size: 1048576, duplicated first: 337036, once_only: 201045
cluster:174, reduced size:1048576, cluster total size: 1572864, duplicated first: 524288, once_only: 0
cluster:175, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:176, reduced size:484875, cluster total size: 1048576, duplicated first: 484875, once_only: 78826
cluster:177, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:178, reduced size:1048576, cluster total size: 1572864, duplicated first: 524288, once_only: 0
cluster:179, reduced size:2386305, cluster total size: 3145728, duplicated first: 505177, once_only: 254246
cluster:180, reduced size:3059260, cluster total size: 3670016, duplicated first: 520245, once_only: 90511
cluster:181, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:182, reduced size:529343, cluster total size: 1048576, duplicated first: 519233, once_only: 0
cluster:183, reduced size:1543050, cluster total size: 2097152, duplicated first: 524288, once_only: 29814
cluster:184, reduced size:2055697, cluster total size: 2621440, duplicated first: 528591, once_only: 37152
cluster:185, reduced size:559329, cluster total size: 1048576, duplicated first: 429860, once_only: 59387
cluster:186, reduced size:524288, cluster total size: 1048576, duplicated first: 524288, once_only: 0
cluster:187, reduced size:2451600, cluster total size: 3145728, duplicated first: 591262, once_only: 102866
cluster:188, reduced size:463520, cluster total size: 1048576, duplicated first: 462256, once_only: 122800
cluster:189, reduced size:525164, cluster total size: 1048576, duplicated first: 523412, once_only: 0

# 2. Message-locked encryption (MLE)

In [18]:
import hashlib
def hash_file(filename):
    sha256_hash = hashlib.sha256()
    with open(filename, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

sha256_list = [[], []]
cnt = 0
for file in all_files:
    # status, output = subprocess.getstatusoutput('sha256sum ' + file)
    output = hash_file(file)
    cnt += 1
    print(cnt, end='\r')
    # output = output.split('  ')
    sha256_list[0].append(file)
    sha256_list[1].append(output)

ssha256_pd=pd.DataFrame(sha256_list)
ssha256_pd = ssha256_pd.T
ssha256_pd.rename(columns={0:'file name', 1:'sha256'},inplace=True)
ssha256_pd

,file name,sha256
0,/home/user/data/partial_data_ubuntu_512KiB/ubu...,34c9972bd555d2cac146d3de4deee757578efe93023843...
1,/home/user/data/partial_data_ubuntu_512KiB/ubu...,7be8f579123b64f988dbd4891cf4838bfe5dae93f877bf...
2,/home/user/data/partial_data_ubuntu_512KiB/ubu...,c547b655218622af4d876708dcaed3e30a39533eaf561a...
3,/home/user/data/partial_data_ubuntu_512KiB/ubu...,964bd39d1decab6749a00cca9866633f9f9050f91aeecb...
4,/home/user/data/partial_data_ubuntu_512KiB/ubu...,4c7e0d70dd23ddb8a9d34edde65e68475155a68e99ae95...
...,...,...
3579,/home/user/data/partial_data_ubuntu_512KiB/ubu...,d27dfa8e1a6d5535069d686d08a0954f692ad7d78c73eb...
3580,/home/user/data/partial_data_ubuntu_512KiB/ubu...,3c847cbfb206502eef05ae3dfdf73a2e1193102727d27f...
3581,/home/user/data/partial_data_ubuntu_512KiB/ubu...,909a9f9b6eb3f681c3593128677a1f3a70468d1fdf9e07...
3582,/home/user/data/partial_data_ubuntu_512KiB/ubu...,42936b926d8d92a604c254c1a64676339456b0138f33b6...
3583,/home/user/data/partial_data_ubuntu_512KiB/ubu...,3d1bbf068a3a34f534d66ab0a6963913bca30b275474eb...

In [19]:
ssha256_pd.describe()

,file name,sha256
count,3584,3584
unique,3584,2989
top,/home/user/data/partial_data_ubuntu_512KiB/ubu...,92344ffeb19494eed14b741489532bd14ab5eae6d87d15...
freq,1,3

In [21]:
ssha256_pd['sha256'].value_counts()

sha256
92344ffeb19494eed14b741489532bd14ab5eae6d87d1583fae2ec4e2f7daf67    3
179de26b1794d57208fa7d733cde7a6898e570fedce800c5d9d4fcf75aea934e    3
e19f66d8d6dd37759f4d867fb5375a13b71647c0c8a8ba8041a563b7ee5457b3    3
5edda385061b63907ae0d3d06fa3ab490286944e393fefa6bb0cc74e418023f2    3
22cb9c343527c70598e42d950b7fe6f06933a5750bc60320b2aedceb778ed81b    3
                                                                   ..
8821bcaf25c252ee6804f3273a37b6d28704d26779071e5cb70c218c4d9302ea    1
988358ce3a3a19153dfbe3f5219575a229165d718f06e2710b9ff6c477320330    1
81537e840dcbf47e83f175111091dac521f7452eb56b5512def7ac17bf17c54e    1
d4de83e7b016ba4c9821068b35f6fc4f8bbe3851cd29abbfcd1dac7a0b650de0    1
aa84b3b6ed69301bf057dc2fa71223d3c15bb5222b85059fd5aa3514e4740727    1
Name: count, Length: 2989, dtype: int64

In [8]:
# Group by 'sha256' and calculate the total size of the duplicated files  
ssha256_pd['file size'] = ssha256_pd['file name'].apply(os.path.getsize)  
grouped = ssha256_pd.groupby('sha256').apply(lambda x: (len(x) - 1) * x['file size'].iloc[0] if len(x) > 1 else 0)  
  
# Calculate the total size of all the duplicated files  
total_deduplicated_size = grouped.sum()  
print(f'{total_deduplicated_size/1024/1024/1024} GiB,  {total_deduplicated_size}')

0.29052734375 GiB,  311951360

/tmp/ipykernel_1947794/2430996357.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = ssha256_pd.groupby('sha256').apply(lambda x: (len(x) - 1) * x['file size'].iloc[0] if len(x) > 1 else 0)

In [9]:
import os
import pandas as pd

ssha256_pd['file size'] = ssha256_pd['file name'].apply(os.path.getsize)

first_file_sizes = ssha256_pd.groupby('sha256').apply(lambda x: x['file size'].iloc[0] if len(x) > 1 else 0)
total_first_file_sizes = first_file_sizes.sum()

total_file_size = ssha256_pd['file size'].sum()
unique_files = ssha256_pd.groupby('sha256').filter(lambda x: len(x) == 1)
total_unique_file_size = unique_files['file size'].sum()


print(f'Total size of files with a unique sha256 hash: {total_unique_file_size/1024/1024/1024} GiB, {total_unique_file_size} bytes')

print(f'Total size of the first files in each duplicate group: {total_first_file_sizes/1024/1024/1024} GiB, {total_first_file_sizes} bytes')
print(f'Total size of all files: {total_file_size/1024/1024/1024} GiB, {total_file_size} bytes')

Total size of files with a unique sha256 hash: 1.23974609375 GiB, 1331167232 bytes
Total size of the first files in each duplicate group: 0.2197265625 GiB, 235929600 bytes
Total size of all files: 1.75 GiB, 1879048192 bytes

/tmp/ipykernel_1947794/1618021712.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  first_file_sizes = ssha256_pd.groupby('sha256').apply(lambda x: x['file size'].iloc[0] if len(x) > 1 else 0)